
var createFFmpegCore = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmpegCore) {
  createFFmpegCore = createFFmpegCore || {};


var e;e||(e=typeof createFFmpegCore !== 'undefined' ? createFFmpegCore : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});e.quit=function(a){if(e.onExit)e.onExit(a);throw new ca(a);};e.exit=da;ea=h=function(){};var fa={},ha;for(ha in e)e.hasOwnProperty(ha)&&(fa[ha]=e[ha]);var ia=[],ja="./this.program";function ka(a,b){throw b;}var la=!1,l=!1,t=!1,ma=!1;la="object"===typeof window;l="function"===typeof importScripts;
t="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ma=!la&&!t&&!l;var u=e.ENVIRONMENT_IS_PTHREAD||!1,x="";function na(a){return e.locateFile?e.locateFile(a,x):x+a}var oa,pa,qa,ra,sa;
if(t){x=l?require("path").dirname(x)+"/":__dirname+"/";oa=function(a,b){ra||(ra=require("fs"));sa||(sa=require("path"));a=sa.normalize(a);return ra.readFileSync(a,b?null:"utf8")};qa=function(a){a=oa(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ja=process.argv[1].replace(/\\/g,"/"));ia=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",z);ka=function(a){process.exit(a)};e.inspect=
function(){return"[Emscripten Module object]"};var ta;try{ta=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=ta.Worker}else if(ma)"undefined"!=typeof read&&(oa=function(a){return read(a)}),qa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ia=scriptArgs:
"undefined"!=typeof arguments&&(ia=arguments),"function"===typeof quit&&(ka=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(la||l)l?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptDir&&(x=_scriptDir),0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="",t?(oa=function(a,b){ra||(ra=
require("fs"));sa||(sa=require("path"));a=sa.normalize(a);return ra.readFileSync(a,b?null:"utf8")},qa=function(a){a=oa(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(oa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(qa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),pa=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";
d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)});t&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var ea=e.print||console.log.bind(console),h=e.printErr||console.warn.bind(console);for(ha in fa)fa.hasOwnProperty(ha)&&(e[ha]=fa[ha]);fa=null;e.arguments&&(ia=e.arguments);e.thisProgram&&(ja=e.thisProgram);e.quit&&(ka=e.quit);var ua,va=0,wa;e.wasmBinary&&(wa=e.wasmBinary);
var noExitRuntime=e.noExitRuntime||!1;"object"!==typeof WebAssembly&&z("no native wasm support detected");var xa,ya,za=!1;function assert(a,b){a||z("Assertion failed: "+b)}function Aa(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function Ba(a,b,c,d){var f={string:function(p){var r=0;if(null!==p&&void 0!==p&&0!==p){var y=(p.length<<2)+1;r=Ca(y);Da(p,A,r,y)}return r},array:function(p){var r=Ca(p.length);B.set(p,r);return r}},g=Aa(a),k=[];a=0;if(d)for(var m=0;m<d.length;m++){var q=f[c[m]];q?(0===a&&(a=C()),k[m]=q(d[m])):k[m]=d[m]}c=g.apply(null,k);c=function(p){return"string"===b?D(p):"boolean"===b?!!p:p}(c);0!==a&&E(a);return c}
function Ea(a){var b=new TextDecoder(a);this.decode=function(c){c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Fa="undefined"!==typeof TextDecoder?new Ea("utf8"):void 0;
function Ga(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Fa)return Fa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function D(a){return a?Ga(A,a,void 0):""}
function Da(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function Ha(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new Ea("utf-16le");function Ia(a){var b=Ha(a)+1,c=H(b);c&&Da(a,B,c,b);return c}function Ja(a){var b=Ha(a)+1,c=Ca(b);Da(a,B,c,b);return c}function Ka(a,b,c){for(var d=0;d<a.length;++d)B[b++>>0]=a.charCodeAt(d);c||(B[b>>0]=0)}var La,B,A,I,Ma,J,K,Na,Oa;u&&(La=e.buffer);
var Pa=e.INITIAL_MEMORY||804913152;
if(u)xa=e.wasmMemory,La=e.buffer;else if(e.wasmMemory)xa=e.wasmMemory;else if(xa=new WebAssembly.Memory({initial:Pa/65536,maximum:Pa/65536,shared:!0}),!(xa.buffer instanceof SharedArrayBuffer))throw h("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),t&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),Error("bad memory");
xa&&(La=xa.buffer);Pa=La.byteLength;var Qa=La;La=Qa;e.HEAP8=B=new Int8Array(Qa);e.HEAP16=I=new Int16Array(Qa);e.HEAP32=J=new Int32Array(Qa);e.HEAPU8=A=new Uint8Array(Qa);e.HEAPU16=Ma=new Uint16Array(Qa);e.HEAPU32=K=new Uint32Array(Qa);e.HEAPF32=Na=new Float32Array(Qa);e.HEAPF64=Oa=new Float64Array(Qa);var L,Ra=[],Sa=[],Ta=[],Ua=[],Va=[];function Wa(){u||(e.noFSInit||M.Mc.yd||M.Mc(),M.ce=!1,O.root=M.Rb(O,{},null),Za(Sa))}function $a(){var a=e.preRun.shift();Ra.unshift(a)}var ab=0,bb=null,cb=null;
function db(){assert(!u,"addRunDependency cannot be used in a pthread worker");ab++;e.monitorRunDependencies&&e.monitorRunDependencies(ab)}function eb(){ab--;e.monitorRunDependencies&&e.monitorRunDependencies(ab);if(0==ab&&(null!==bb&&(clearInterval(bb),bb=null),cb)){var a=cb;cb=null;a()}}e.preloadedImages={};e.preloadedAudios={};
function z(a){if(e.onAbort)e.onAbort(a);u&&console.error("Pthread aborting at "+Error().stack);h(a);za=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function fb(){return P.startsWith("data:application/octet-stream;base64,")}var P;P="ffmpeg-core.wasm";fb()||(P=na(P));function gb(){var a=P;try{if(a==P&&wa)return new Uint8Array(wa);if(qa)return qa(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function hb(){if(!wa&&(la||l)){if("function"===typeof fetch&&!P.startsWith("file://"))return fetch(P,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+P+"'";return a.arrayBuffer()}).catch(function(){return gb()});if(pa)return new Promise(function(a,b){pa(P,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return gb()})}
var S,T,jb={5410468:function(){throw"Canceled!";},5410486:function(a,b){setTimeout(function(){ib(a,b)},0)}};function Za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Ke;"number"===typeof c?void 0===b.Ac?L.get(c)():L.get(c)(b.Ac):c(void 0===b.Ac?null:b.Ac)}}}
function kb(a,b){if(0>=a||a>B.length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(J,lb>>2),d=0;if(c==a&&Atomics.compareExchange(J,lb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(J,a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}e._emscripten_futex_wake=kb;
function mb(a){if(u)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cancelThread!";U.kc[a].worker.postMessage({cmd:"cancel"})}function nb(a){if(u)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=U.kc[a];b&&(J[a+12>>2]=0,U.ed(b.worker))}
var U={rc:[],qc:[],Hd:[],Of:function(){},Qe:function(){for(var a=H(228),b=0;57>b;++b)K[a/4+b]=0;J[a+12>>2]=a;b=a+152;J[b>>2]=b;var c=H(512);for(b=0;128>b;++b)K[c/4+b]=0;Atomics.store(K,a+100>>2,c);Atomics.store(K,a+40>>2,a);ob(a,!l,1);pb(a)},Re:function(){U.receiveObjectTransfer=U.hf;U.threadInit=U.tf;U.threadCancel=U.rf;U.threadExit=U.sf;U.setExitStatus=U.mf},kc:{},jd:[],ie:function(){for(;0<U.jd.length;)U.jd.pop()();u&&qb()&&rb()},je:function(a,b){Atomics.store(K,a+56>>2,1);Atomics.store(K,a+60>>
2,0);U.ie();Atomics.store(K,a+4>>2,b);Atomics.store(K,a+0>>2,1);kb(a+0,2147483647);ob(0,0,0)},mf:function(){},sf:function(a){var b=qb();b&&(U.je(b,a),u&&postMessage({cmd:"exit"}))},rf:function(){U.je(qb(),-1);postMessage({cmd:"cancelDone"})},qf:function(){for(var a in U.kc){var b=U.kc[a];b&&b.worker&&U.ed(b.worker)}U.kc={};for(a=0;a<U.rc.length;++a){var c=U.rc[a];c.terminate()}U.rc=[];for(a=0;a<U.qc.length;++a)c=U.qc[a],b=c.dc,U.ud(b),c.terminate();U.qc=[]},ud:function(a){if(a){if(a.lc){var b=J[a.lc+
100>>2];J[a.lc+100>>2]=0;sb(b);sb(a.lc)}a.lc=0;a.qd&&a.yc&&sb(a.yc);a.yc=0;a.worker&&(a.worker.dc=null)}},ed:function(a){U.kf(function(){delete U.kc[a.dc.lc];U.rc.push(a);U.qc.splice(U.qc.indexOf(a),1);U.ud(a.dc);a.dc=void 0})},kf:function(a){J[tb>>2]=0;try{a()}finally{J[tb>>2]=1}},hf:function(){},tf:function(){for(var a in U.Hd)U.Hd[a]()},Ve:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.dc&&(U.Fe=a.dc.lc);if(d.targetThread&&d.targetThread!=qb()){var g=U.kc[d.Zf];g?g.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)vb();else if("spawnThread"===f)wb(c.data);else if("cleanupThread"===f)nb(d.thread);else if("killThread"===f){c=d.thread;if(u)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";J[c+12>>2]=0;c=U.kc[c];c.worker.terminate();
U.ud(c);U.qc.splice(U.qc.indexOf(c.worker),1);c.worker.dc=void 0}else if("cancelThread"===f)mb(d.thread);else if("loaded"===f)a.loaded=!0,b&&b(a),a.Sc&&(a.Sc(),delete a.Sc);else if("print"===f)ea("Thread "+d.threadId+": "+d.text);else if("printErr"===f)h("Thread "+d.threadId+": "+d.text);else if("alert"===f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.dc&&Atomics.load(K,a.dc.lc+64>>2)&&U.ed(a);else if("exitProcess"===f)try{da(d.returnCode)}catch(k){if(k instanceof ca)return;throw k;
}else"cancelDone"===f?U.ed(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):h("worker sent an unknown command "+f));U.Fe=void 0};a.onerror=function(c){h("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};t&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:e.mainScriptUrlOrBlob||_scriptDir,wasmMemory:xa,wasmModule:ya})},ue:function(){var a=na("ffmpeg-core.worker.js");
U.rc.push(new Worker(a))},Me:function(){0==U.rc.length&&(U.ue(),U.Ve(U.rc[0]));return U.rc.pop()},Cf:function(a){for(a=performance.now()+a;performance.now()<a;);}};e.establishStackSpace=function(a,b){yb(a,b);E(a)};e.invokeEntryPoint=function(a,b){return L.get(a)(b)};var zb=0;function Ab(){return noExitRuntime||0<zb}e.keepRuntimeAlive=Ab;var Bb;
t?Bb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:u?Bb=function(){return performance.now()-e.__performance_now_clock_drift}:"undefined"!==typeof dateNow?Bb=dateNow:Bb=function(){return performance.now()};function Cb(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Bb();else return J[Db()>>2]=28,-1;J[b>>2]=a/1E3|0;J[b+4>>2]=a%1E3*1E6|0;return 0}function Eb(a,b){if(u)return V(1,1,a,b);Ua.unshift({Ke:a,Ac:b})}function Fb(a,b){U.jd.push(function(){L.get(a)(b)})}
function Gb(a,b){a=new Date(1E3*J[a>>2]);J[b>>2]=a.getUTCSeconds();J[b+4>>2]=a.getUTCMinutes();J[b+8>>2]=a.getUTCHours();J[b+12>>2]=a.getUTCDate();J[b+16>>2]=a.getUTCMonth();J[b+20>>2]=a.getUTCFullYear()-1900;J[b+24>>2]=a.getUTCDay();J[b+36>>2]=0;J[b+32>>2]=0;J[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;Gb.Kd||(Gb.Kd=Ia("GMT"));J[b+40>>2]=Gb.Kd;return b}
function Hb(){function a(k){return(k=k.toTimeString().match(/\(([A-Za-z ]+)\)$/))?k[1]:"GMT"}if(u)return V(2,1);if(!Hb.we){Hb.we=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var f=d.getTimezoneOffset(),g=Math.max(b,f);J[Ib()>>2]=60*g;J[Jb()>>2]=Number(b!=f);c=a(c);d=a(d);c=Ia(c);d=Ia(d);f<b?(J[Kb()>>2]=c,J[Kb()+4>>2]=d):(J[Kb()>>2]=d,J[Kb()+4>>2]=c)}}
function Lb(a,b){Hb();a=new Date(1E3*J[a>>2]);J[b>>2]=a.getSeconds();J[b+4>>2]=a.getMinutes();J[b+8>>2]=a.getHours();J[b+12>>2]=a.getDate();J[b+16>>2]=a.getMonth();J[b+20>>2]=a.getFullYear()-1900;J[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);J[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;J[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;J[b+32>>2]=a;a=J[Kb()+(a?4:0)>>2];
J[b+40>>2]=a;return b}function Mb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Nb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Mb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ob(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Pb(a){if("/"===a)return"/";a=Nb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Qb(a,b){return Nb(a+"/"+b)}
function Rb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(t)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){z("randomDevice")}}
function Sb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:M.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Mb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function Tb(a,b){function c(k){for(var m=0;m<k.length&&""===k[m];m++);for(var q=k.length-1;0<=q&&""===k[q];q--);return m>q?[]:k.slice(m,q-m+1)}a=Sb(a).substr(1);b=Sb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var Ub=[];function Vb(a,b){Ub[a]={input:[],output:[],Ec:b};M.Gd(a,Wb)}
var Wb={open:function(a){var b=Ub[a.node.rdev];if(!b)throw new M.Kb(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ec.flush(a.tty)},flush:function(a){a.tty.Ec.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ec.Zd)throw new M.Kb(60);for(var f=0,g=0;g<d;g++){try{var k=a.tty.Ec.Zd(a.tty)}catch(m){throw new M.Kb(29);}if(void 0===k&&0===f)throw new M.Kb(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Ec.Dd)throw new M.Kb(60);
try{for(var f=0;f<d;f++)a.tty.Ec.Dd(a.tty,b[c+f])}catch(g){throw new M.Kb(29);}d&&(a.node.timestamp=Date.now());return f}},Yb={Zd:function(a){if(!a.input.length){var b=null;if(t){var c=Buffer.zc?Buffer.zc(256):new Buffer(256),d=0;try{d=ra.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Xb(b,!0)}return a.input.shift()},Dd:function(a,b){null===b||10===b?(ea(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ea(Ga(a.output,0)),a.output=[])}},Zb={Dd:function(a,b){null===b||10===b?(h(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Ga(a.output,0)),a.output=[])}},W={jc:null,Rb:function(){return W.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(M.Se(c)||M.isFIFO(c))throw new M.Kb(63);W.jc||(W.jc={dir:{node:{fc:W.Lb.fc,Wb:W.Lb.Wb,lookup:W.Lb.lookup,mc:W.Lb.mc,rename:W.Lb.rename,unlink:W.Lb.unlink,rmdir:W.Lb.rmdir,readdir:W.Lb.readdir,symlink:W.Lb.symlink},stream:{$b:W.Mb.$b}},file:{node:{fc:W.Lb.fc,Wb:W.Lb.Wb},stream:{$b:W.Mb.$b,read:W.Mb.read,write:W.Mb.write,Lc:W.Mb.Lc,Cc:W.Mb.Cc,Dc:W.Mb.Dc}},link:{node:{fc:W.Lb.fc,Wb:W.Lb.Wb,readlink:W.Lb.readlink},stream:{}},Nd:{node:{fc:W.Lb.fc,Wb:W.Lb.Wb},
stream:M.ye}});c=M.createNode(a,b,c,d);M.Tb(c.mode)?(c.Lb=W.jc.dir.node,c.Mb=W.jc.dir.stream,c.Ob={}):M.isFile(c.mode)?(c.Lb=W.jc.file.node,c.Mb=W.jc.file.stream,c.Qb=0,c.Ob=null):M.tc(c.mode)?(c.Lb=W.jc.link.node,c.Mb=W.jc.link.stream):M.Nc(c.mode)&&(c.Lb=W.jc.Nd.node,c.Mb=W.jc.Nd.stream);c.timestamp=Date.now();a&&(a.Ob[b]=c,a.timestamp=c.timestamp);return c},Lf:function(a){return a.Ob?a.Ob.subarray?a.Ob.subarray(0,a.Qb):new Uint8Array(a.Ob):new Uint8Array(0)},Ud:function(a,b){var c=a.Ob?a.Ob.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ob,a.Ob=new Uint8Array(b),0<a.Qb&&a.Ob.set(c.subarray(0,a.Qb),0))},jf:function(a,b){if(a.Qb!=b)if(0==b)a.Ob=null,a.Qb=0;else{var c=a.Ob;a.Ob=new Uint8Array(b);c&&a.Ob.set(c.subarray(0,Math.min(b,a.Qb)));a.Qb=b}},Lb:{fc:function(a){var b={};b.dev=M.Nc(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;M.Tb(a.mode)?b.size=4096:M.isFile(a.mode)?b.size=a.Qb:M.tc(a.mode)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.ve=4096;b.blocks=Math.ceil(b.size/b.ve);return b},Wb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&W.jf(a,b.size)},lookup:function(){throw M.vd[44];},mc:function(a,b,c,d){return W.createNode(a,b,c,d)},rename:function(a,b,c){if(M.Tb(a.mode)){try{var d=M.hc(b,c)}catch(g){}if(d)for(var f in d.Ob)throw new M.Kb(55);}delete a.parent.Ob[a.name];
a.parent.timestamp=Date.now();a.name=c;b.Ob[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Ob[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=M.hc(a,b),d;for(d in c.Ob)throw new M.Kb(55);delete a.Ob[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Ob)a.Ob.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=W.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!M.tc(a.mode))throw new M.Kb(28);return a.link}},
Mb:{read:function(a,b,c,d,f){var g=a.node.Ob;if(f>=a.node.Qb)return 0;a=Math.min(a.node.Qb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ob||a.Ob.subarray)){if(g)return a.Ob=b.subarray(c,c+d),a.Qb=d;if(0===a.Qb&&0===f)return a.Ob=b.slice(c,c+d),a.Qb=d;if(f+d<=a.Qb)return a.Ob.set(b.subarray(c,c+d),f),d}W.Ud(a,f+d);if(a.Ob.subarray&&b.subarray)a.Ob.set(b.subarray(c,
c+d),f);else for(g=0;g<d;g++)a.Ob[f+g]=b[c+g];a.Qb=Math.max(a.Qb,f+d);return d},$b:function(a,b,c){1===c?b+=a.position:2===c&&M.isFile(a.node.mode)&&(b+=a.node.Qb);if(0>b)throw new M.Kb(28);return b},Lc:function(a,b,c){W.Ud(a.node,b+c);a.node.Qb=Math.max(a.node.Qb,b+c)},Cc:function(a,b,c,d,f,g){if(0!==b)throw new M.Kb(28);if(!M.isFile(a.node.mode))throw new M.Kb(43);a=a.node.Ob;if(g&2||a.buffer!==La){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=
65536*Math.ceil(c/65536);for(b=H(g);c<g;)B[b+c++]=0;c=b;if(!c)throw new M.Kb(48);B.set(a,c)}else d=!1,c=a.byteOffset;return{gf:c,pd:d}},Dc:function(a,b,c,d,f){if(!M.isFile(a.node.mode))throw new M.Kb(43);if(f&2)return 0;W.Mb.write(a,b,0,d,c,!1);return 0}}},M={root:null,Qc:[],Rd:{},streams:[],af:1,ic:null,Qd:"/",yd:!1,ce:!0,Vb:{},me:{fe:{qe:1,re:2}},Kb:null,vd:{},Ie:null,hd:0,Pb:function(a,b){a=Sb(M.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={td:!0,Fd:0},d;for(d in c)void 0===b[d]&&(b[d]=
c[d]);if(8<b.Fd)throw new M.Kb(32);a=Mb(a.split("/").filter(function(k){return!!k}),!1);var f=M.root;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=M.hc(f,a[d]);c=Qb(c,a[d]);M.uc(f)&&(!g||g&&b.td)&&(f=f.Pc.root);if(!g||b.cc)for(g=0;M.tc(f.mode);)if(f=M.readlink(c),c=Sb(Ob(c),f),f=M.Pb(c,{Fd:b.Fd}).node,40<g++)throw new M.Kb(32);}return{path:c,node:f}},oc:function(a){for(var b;;){if(M.$c(a))return a=a.Rb.de,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},
xd:function(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%M.ic.length},ae:function(a){var b=M.xd(a.parent.id,a.name);a.wc=M.ic[b];M.ic[b]=a},be:function(a){var b=M.xd(a.parent.id,a.name);if(M.ic[b]===a)M.ic[b]=a.wc;else for(b=M.ic[b];b;){if(b.wc===a){b.wc=a.wc;break}b=b.wc}},hc:function(a,b){var c=M.Ye(a);if(c)throw new M.Kb(c,a);for(c=M.ic[M.xd(a.id,b)];c;c=c.wc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return M.lookup(a,b)},createNode:function(a,b,c,
d){a=new M.ne(a,b,c,d);M.ae(a);return a},sd:function(a){M.be(a)},$c:function(a){return a===a.parent},uc:function(a){return!!a.Pc},isFile:function(a){return 32768===(a&61440)},Tb:function(a){return 16384===(a&61440)},tc:function(a){return 40960===(a&61440)},Nc:function(a){return 8192===(a&61440)},Se:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},Je:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},$e:function(a){var b=M.Je[a];
if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},Vd:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},pc:function(a,b){if(M.ce)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Ye:function(a){var b=M.pc(a,"x");return b?b:a.Lb.lookup?0:2},Cd:function(a,b){try{return M.hc(a,b),20}catch(c){}return M.pc(a,"wx")},ad:function(a,b,c){try{var d=M.hc(a,b)}catch(f){return f.Nb}if(a=
M.pc(a,"wx"))return a;if(c){if(!M.Tb(d.mode))return 54;if(M.$c(d)||M.oc(d)===M.cwd())return 10}else if(M.Tb(d.mode))return 31;return 0},Ze:function(a,b){return a?M.tc(a.mode)?32:M.Tb(a.mode)&&("r"!==M.Vd(b)||b&512)?31:M.pc(a,M.Vd(b)):44},pe:4096,bf:function(a,b){b=b||M.pe;for(a=a||0;a<=b;a++)if(!M.streams[a])return a;throw new M.Kb(33);},ec:function(a){return M.streams[a]},Pd:function(a,b,c){M.nd||(M.nd=function(){},M.nd.prototype={object:{get:function(){return this.node},set:function(g){this.node=
g}}});var d=new M.nd,f;for(f in a)d[f]=a[f];a=d;b=M.bf(b,c);a.fd=b;return M.streams[b]=a},ze:function(a){M.streams[a]=null},ye:{open:function(a){a.Mb=M.Le(a.node.rdev).Mb;a.Mb.open&&a.Mb.open(a)},$b:function(){throw new M.Kb(70);}},Bd:function(a){return a>>8},Qf:function(a){return a&255},vc:function(a,b){return a<<8|b},Gd:function(a,b){M.Rd[a]={Mb:b}},Le:function(a){return M.Rd[a]},Yd:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.Qc)}return b},le:function(a,b){function c(k){M.hd--;
return b(k)}function d(k){if(k){if(!d.Ge)return d.Ge=!0,c(k)}else++g>=f.length&&c(null)}"function"===typeof a&&(b=a,a=!1);M.hd++;1<M.hd&&h("warning: "+M.hd+" FS.syncfs operations in flight at once, probably just doing extra work");var f=M.Yd(M.root.Rb),g=0;f.forEach(function(k){if(!k.type.le)return d(null);k.type.le(k,a,d)})},Rb:function(a,b,c){var d="/"===c,f=!c;if(d&&M.root)throw new M.Kb(10);if(!d&&!f){var g=M.Pb(c,{td:!1});c=g.path;g=g.node;if(M.uc(g))throw new M.Kb(10);if(!M.Tb(g.mode))throw new M.Kb(54);
}b={type:a,Vf:b,de:c,Qc:[]};a=a.Rb(b);a.Rb=b;b.root=a;d?M.root=a:g&&(g.Pc=b,g.Rb&&g.Rb.Qc.push(b));return a},ag:function(a){a=M.Pb(a,{td:!1});if(!M.uc(a.node))throw new M.Kb(28);a=a.node;var b=a.Pc,c=M.Yd(b);Object.keys(M.ic).forEach(function(d){for(d=M.ic[d];d;){var f=d.wc;c.includes(d.Rb)&&M.sd(d);d=f}});a.Pc=null;a.Rb.Qc.splice(a.Rb.Qc.indexOf(b),1)},lookup:function(a,b){return a.Lb.lookup(a,b)},mc:function(a,b,c){var d=M.Pb(a,{parent:!0}).node;a=Pb(a);if(!a||"."===a||".."===a)throw new M.Kb(28);
var f=M.Cd(d,a);if(f)throw new M.Kb(f);if(!d.Lb.mc)throw new M.Kb(63);return d.Lb.mc(d,a,b,c)},create:function(a,b){return M.mc(a,(void 0!==b?b:438)&4095|32768,0)},mkdir:function(a,b){return M.mc(a,(void 0!==b?b:511)&1023|16384,0)},Sf:function(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{M.mkdir(c,b)}catch(f){if(20!=f.Nb)throw f;}}},bd:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return M.mc(a,b|8192,c)},symlink:function(a,b){if(!Sb(a))throw new M.Kb(44);var c=
M.Pb(b,{parent:!0}).node;if(!c)throw new M.Kb(44);b=Pb(b);var d=M.Cd(c,b);if(d)throw new M.Kb(d);if(!c.Lb.symlink)throw new M.Kb(63);return c.Lb.symlink(c,b,a)},rename:function(a,b){var c=Ob(a),d=Ob(b),f=Pb(a),g=Pb(b);var k=M.Pb(a,{parent:!0});var m=k.node;k=M.Pb(b,{parent:!0});k=k.node;if(!m||!k)throw new M.Kb(44);if(m.Rb!==k.Rb)throw new M.Kb(75);var q=M.hc(m,f);d=Tb(a,d);if("."!==d.charAt(0))throw new M.Kb(28);d=Tb(b,c);if("."!==d.charAt(0))throw new M.Kb(55);try{var p=M.hc(k,g)}catch(r){}if(q!==
p){c=M.Tb(q.mode);if(f=M.ad(m,f,c))throw new M.Kb(f);if(f=p?M.ad(k,g,c):M.Cd(k,g))throw new M.Kb(f);if(!m.Lb.rename)throw new M.Kb(63);if(M.uc(q)||p&&M.uc(p))throw new M.Kb(10);if(k!==m&&(f=M.pc(m,"w")))throw new M.Kb(f);try{M.Vb.willMovePath&&M.Vb.willMovePath(a,b)}catch(r){h("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}M.be(q);try{m.Lb.rename(q,k,g)}catch(r){throw r;}finally{M.ae(q)}try{if(M.Vb.onMovePath)M.Vb.onMovePath(a,b)}catch(r){h("FS.trackingDelegate['onMovePath']('"+
a+"', '"+b+"') threw an exception: "+r.message)}}},rmdir:function(a){var b=M.Pb(a,{parent:!0}).node,c=Pb(a),d=M.hc(b,c),f=M.ad(b,c,!0);if(f)throw new M.Kb(f);if(!b.Lb.rmdir)throw new M.Kb(63);if(M.uc(d))throw new M.Kb(10);try{M.Vb.willDeletePath&&M.Vb.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.Lb.rmdir(b,c);M.sd(d);try{if(M.Vb.onDeletePath)M.Vb.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+
g.message)}},readdir:function(a){a=M.Pb(a,{cc:!0}).node;if(!a.Lb.readdir)throw new M.Kb(54);return a.Lb.readdir(a)},unlink:function(a){var b=M.Pb(a,{parent:!0}).node,c=Pb(a),d=M.hc(b,c),f=M.ad(b,c,!1);if(f)throw new M.Kb(f);if(!b.Lb.unlink)throw new M.Kb(63);if(M.uc(d))throw new M.Kb(10);try{M.Vb.willDeletePath&&M.Vb.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.Lb.unlink(b,c);M.sd(d);try{if(M.Vb.onDeletePath)M.Vb.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+g.message)}},readlink:function(a){a=M.Pb(a).node;if(!a)throw new M.Kb(44);if(!a.Lb.readlink)throw new M.Kb(28);return Sb(M.oc(a.parent),a.Lb.readlink(a))},stat:function(a,b){a=M.Pb(a,{cc:!b}).node;if(!a)throw new M.Kb(44);if(!a.Lb.fc)throw new M.Kb(63);return a.Lb.fc(a)},lstat:function(a){return M.stat(a,!0)},chmod:function(a,b,c){a="string"===typeof a?M.Pb(a,{cc:!c}).node:a;if(!a.Lb.Wb)throw new M.Kb(63);a.Lb.Wb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:function(a,
b){M.chmod(a,b,!0)},fchmod:function(a,b){a=M.ec(a);if(!a)throw new M.Kb(8);M.chmod(a.node,b)},chown:function(a,b,c,d){a="string"===typeof a?M.Pb(a,{cc:!d}).node:a;if(!a.Lb.Wb)throw new M.Kb(63);a.Lb.Wb(a,{timestamp:Date.now()})},lchown:function(a,b,c){M.chown(a,b,c,!0)},fchown:function(a,b,c){a=M.ec(a);if(!a)throw new M.Kb(8);M.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new M.Kb(28);a="string"===typeof a?M.Pb(a,{cc:!0}).node:a;if(!a.Lb.Wb)throw new M.Kb(63);if(M.Tb(a.mode))throw new M.Kb(31);
if(!M.isFile(a.mode))throw new M.Kb(28);var c=M.pc(a,"w");if(c)throw new M.Kb(c);a.Lb.Wb(a,{size:b,timestamp:Date.now()})},Kf:function(a,b){a=M.ec(a);if(!a)throw new M.Kb(8);if(0===(a.flags&2097155))throw new M.Kb(28);M.truncate(a.node,b)},bg:function(a,b,c){a=M.Pb(a,{cc:!0}).node;a.Lb.Wb(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,d,f){if(""===a)throw new M.Kb(44);b="string"===typeof b?M.$e(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Nb(a);
try{g=M.Pb(a,{cc:!(b&131072)}).node}catch(m){}}var k=!1;if(b&64)if(g){if(b&128)throw new M.Kb(20);}else g=M.mc(a,c,0),k=!0;if(!g)throw new M.Kb(44);M.Nc(g.mode)&&(b&=-513);if(b&65536&&!M.Tb(g.mode))throw new M.Kb(54);if(!k&&(c=M.Ze(g,b)))throw new M.Kb(c);b&512&&M.truncate(g,0);b&=-131713;d=M.Pd({node:g,path:M.oc(g),flags:b,seekable:!0,position:0,Mb:g.Mb,zf:[],error:!1},d,f);d.Mb.open&&d.Mb.open(d);!e.logReadFiles||b&1||(M.Ed||(M.Ed={}),a in M.Ed||(M.Ed[a]=1,h("FS.trackingDelegate error on read file: "+
a)));try{M.Vb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=M.me.fe.qe),0!==(b&2097155)&&(f|=M.me.fe.re),M.Vb.onOpenFile(a,f))}catch(m){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d},close:function(a){if(M.Oc(a))throw new M.Kb(8);a.sc&&(a.sc=null);try{a.Mb.close&&a.Mb.close(a)}catch(b){throw b;}finally{M.ze(a.fd)}a.fd=null},Oc:function(a){return null===a.fd},$b:function(a,b,c){if(M.Oc(a))throw new M.Kb(8);if(!a.seekable||!a.Mb.$b)throw new M.Kb(70);if(0!=c&&
1!=c&&2!=c)throw new M.Kb(28);a.position=a.Mb.$b(a,b,c);a.zf=[];return a.position},read:function(a,b,c,d,f){if(0>d||0>f)throw new M.Kb(28);if(M.Oc(a))throw new M.Kb(8);if(1===(a.flags&2097155))throw new M.Kb(8);if(M.Tb(a.node.mode))throw new M.Kb(31);if(!a.Mb.read)throw new M.Kb(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new M.Kb(70);b=a.Mb.read(a,b,c,d,f);g||(a.position+=b);return b},write:function(a,b,c,d,f,g){if(0>d||0>f)throw new M.Kb(28);if(M.Oc(a))throw new M.Kb(8);
if(0===(a.flags&2097155))throw new M.Kb(8);if(M.Tb(a.node.mode))throw new M.Kb(31);if(!a.Mb.write)throw new M.Kb(28);a.seekable&&a.flags&1024&&M.$b(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new M.Kb(70);b=a.Mb.write(a,b,c,d,f,g);k||(a.position+=b);try{if(a.path&&M.Vb.onWriteToFile)M.Vb.onWriteToFile(a.path)}catch(m){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b},Lc:function(a,b,c){if(M.Oc(a))throw new M.Kb(8);
if(0>b||0>=c)throw new M.Kb(28);if(0===(a.flags&2097155))throw new M.Kb(8);if(!M.isFile(a.node.mode)&&!M.Tb(a.node.mode))throw new M.Kb(43);if(!a.Mb.Lc)throw new M.Kb(138);a.Mb.Lc(a,b,c)},Cc:function(a,b,c,d,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new M.Kb(2);if(1===(a.flags&2097155))throw new M.Kb(2);if(!a.Mb.Cc)throw new M.Kb(43);return a.Mb.Cc(a,b,c,d,f,g)},Dc:function(a,b,c,d,f){return a&&a.Mb.Dc?a.Mb.Dc(a,b,c,d,f):0},Uf:function(){return 0},Bc:function(a,b,c){if(!a.Mb.Bc)throw new M.Kb(59);
return a.Mb.Bc(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=M.open(a,b.flags);a=M.stat(a).size;var f=new Uint8Array(a);M.read(d,f,0,a,0);"utf8"===b.encoding?c=Ga(f,0):"binary"===b.encoding&&(c=f);M.close(d);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||577;a=M.open(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(Ha(b)+
1);b=Da(b,d,0,d.length);M.write(a,d,0,b,void 0,c.xe)}else if(ArrayBuffer.isView(b))M.write(a,b,0,b.byteLength,void 0,c.xe);else throw Error("Unsupported data type");M.close(a)},cwd:function(){return M.Qd},chdir:function(a){a=M.Pb(a,{cc:!0});if(null===a.node)throw new M.Kb(44);if(!M.Tb(a.node.mode))throw new M.Kb(54);var b=M.pc(a.node,"x");if(b)throw new M.Kb(b);M.Qd=a.path},Be:function(){M.mkdir("/tmp");M.mkdir("/home");M.mkdir("/home/web_user")},Ae:function(){M.mkdir("/dev");M.Gd(M.vc(1,3),{read:function(){return 0},
write:function(b,c,d,f){return f}});M.bd("/dev/null",M.vc(1,3));Vb(M.vc(5,0),Yb);Vb(M.vc(6,0),Zb);M.bd("/dev/tty",M.vc(5,0));M.bd("/dev/tty1",M.vc(6,0));var a=Rb();M.nc("/dev","random",a);M.nc("/dev","urandom",a);M.mkdir("/dev/shm");M.mkdir("/dev/shm/tmp")},De:function(){M.mkdir("/proc");var a=M.mkdir("/proc/self");M.mkdir("/proc/self/fd");M.Rb({Rb:function(){var b=M.createNode(a,"fd",16895,73);b.Lb={lookup:function(c,d){var f=M.ec(+d);if(!f)throw new M.Kb(8);c={parent:null,Rb:{de:"fake"},Lb:{readlink:function(){return f.path}}};
return c.parent=c}};return b}},{},"/proc/self/fd")},Ee:function(){e.stdin?M.nc("/dev","stdin",e.stdin):M.symlink("/dev/tty","/dev/stdin");e.stdout?M.nc("/dev","stdout",null,e.stdout):M.symlink("/dev/tty","/dev/stdout");e.stderr?M.nc("/dev","stderr",null,e.stderr):M.symlink("/dev/tty1","/dev/stderr");M.open("/dev/stdin",0);M.open("/dev/stdout",1);M.open("/dev/stderr",1)},Td:function(){M.Kb||(M.Kb=function(a,b){this.node=b;this.lf=function(c){this.Nb=c};this.lf(a);this.message="FS error"},M.Kb.prototype=
Error(),M.Kb.prototype.constructor=M.Kb,[44].forEach(function(a){M.vd[a]=new M.Kb(a);M.vd[a].stack="<generic error, no stack>"}))},pf:function(){M.Td();M.ic=Array(4096);M.Rb(W,{},"/");M.Be();M.Ae();M.De();M.Ie={MEMFS:W}},Mc:function(a,b,c){M.Mc.yd=!0;M.Td();e.stdin=a||e.stdin;e.stdout=b||e.stdout;e.stderr=c||e.stderr;M.Ee()},quit:function(){M.Mc.yd=!1;var a=e._fflush;a&&a(0);for(a=0;a<M.streams.length;a++){var b=M.streams[a];b&&M.close(b)}},wd:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},
Jf:function(a,b){a=M.rd(a,b);return a.exists?a.object:null},rd:function(a,b){try{var c=M.Pb(a,{cc:!b});a=c.path}catch(f){}var d={$c:!1,exists:!1,error:0,name:null,path:null,object:null,cf:!1,ef:null,df:null};try{c=M.Pb(a,{parent:!0}),d.cf=!0,d.ef=c.path,d.df=c.node,d.name=Pb(a),c=M.Pb(a,{cc:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.$c="/"===c.path}catch(f){d.error=f.Nb}return d},Gf:function(a,b){a="string"===typeof a?a:M.oc(a);for(b=b.split("/").reverse();b.length;){var c=
b.pop();if(c){var d=Qb(a,c);try{M.mkdir(d)}catch(f){}a=d}}return d},Ce:function(a,b,c,d,f){a=Qb("string"===typeof a?a:M.oc(a),b);return M.create(a,M.wd(d,f))},Od:function(a,b,c,d,f,g){a=b?Qb("string"===typeof a?a:M.oc(a),b):a;d=M.wd(d,f);f=M.create(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}M.chmod(f,d|146);a=M.open(f,577);M.write(a,c,0,c.length,0,g);M.close(a);M.chmod(f,d)}return f},nc:function(a,b,c,d){a=Qb("string"===typeof a?a:
M.oc(a),b);b=M.wd(!!c,!!d);M.nc.Bd||(M.nc.Bd=64);var f=M.vc(M.nc.Bd++,0);M.Gd(f,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,k,m,q){for(var p=0,r=0;r<q;r++){try{var y=c()}catch(F){throw new M.Kb(29);}if(void 0===y&&0===p)throw new M.Kb(6);if(null===y||void 0===y)break;p++;k[m+r]=y}p&&(g.node.timestamp=Date.now());return p},write:function(g,k,m,q){for(var p=0;p<q;p++)try{d(k[m+p])}catch(r){throw new M.Kb(29);}q&&(g.node.timestamp=Date.now());
return p}});return M.bd(a,b,f)},Wd:function(a){if(a.zd||a.Te||a.link||a.Ob)return!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(oa)try{a.Ob=Xb(oa(a.url),!0),a.Qb=a.Ob.length}catch(b){throw new M.Kb(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Ff:function(a,b,c,d,f){function g(){this.Ad=
!1;this.zc=[]}g.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.chunkSize;return this.$d(p/this.chunkSize|0)[r]}};g.prototype.oe=function(p){this.$d=p};g.prototype.Md=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),y,F=(y=p.getResponseHeader("Accept-Ranges"))&&"bytes"===y;p=(y=p.getResponseHeader("Content-Encoding"))&&
"gzip"===y;var n=1048576;F||(n=r);var v=this;v.oe(function(w){var N=w*n,Q=(w+1)*n-1;Q=Math.min(Q,r-1);if("undefined"===typeof v.zc[w]){var ub=v.zc;if(N>Q)throw Error("invalid range ("+N+", "+Q+") or no bytes requested!");if(Q>r-1)throw Error("only "+r+" bytes available! programmer error!");var G=new XMLHttpRequest;G.open("GET",c,!1);r!==n&&G.setRequestHeader("Range","bytes="+N+"-"+Q);"undefined"!=typeof Uint8Array&&(G.responseType="arraybuffer");G.overrideMimeType&&G.overrideMimeType("text/plain; charset=x-user-defined");
G.send(null);if(!(200<=G.status&&300>G.status||304===G.status))throw Error("Couldn't load "+c+". Status: "+G.status);N=void 0!==G.response?new Uint8Array(G.response||[]):Xb(G.responseText||"",!0);ub[w]=N}if("undefined"===typeof v.zc[w])throw Error("doXHR failed!");return v.zc[w]});if(p||!r)n=r=1,n=r=this.$d(0).length,ea("LazyFiles on gzip forces download of the whole file when length is accessed");this.te=r;this.se=n;this.Ad=!0};if("undefined"!==typeof XMLHttpRequest){if(!l)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var k=new g;Object.defineProperties(k,{length:{get:function(){this.Ad||this.Md();return this.te}},chunkSize:{get:function(){this.Ad||this.Md();return this.se}}});k={zd:!1,Ob:k}}else k={zd:!1,url:c};var m=M.Ce(a,b,k,d,f);k.Ob?m.Ob=k.Ob:k.url&&(m.Ob=null,m.url=k.url);Object.defineProperties(m,{Qb:{get:function(){return this.Ob.length}}});var q={};Object.keys(m.Mb).forEach(function(p){var r=m.Mb[p];q[p]=function(){M.Wd(m);return r.apply(null,arguments)}});q.read=function(p,r,y,F,n){M.Wd(m);p=p.node.Ob;
if(n>=p.length)return 0;F=Math.min(p.length-n,F);if(p.slice)for(var v=0;v<F;v++)r[y+v]=p[n+v];else for(v=0;v<F;v++)r[y+v]=p.get(n+v);return F};m.Mb=q;return m},Hf:function(a,b,c,d,f,g,k,m,q,p){function r(F){function n(w){p&&p();m||M.Od(a,b,w,d,f,q);g&&g();eb()}var v=!1;e.preloadPlugins.forEach(function(w){!v&&w.canHandle(y)&&(w.handle(F,y,n,function(){k&&k();eb()}),v=!0)});v||n(F)}$b.Mc();var y=b?Sb(Qb(a,b)):a;db();"string"==typeof c?$b.Af(c,function(F){r(F)},k):r(c)},indexedDB:function(){return window.indexedDB||
window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},Id:function(){return"EM_FS_"+window.location.pathname},Jd:20,Kc:"FILE_DATA",Yf:function(a,b,c){b=b||function(){};c=c||function(){};var d=M.indexedDB();try{var f=d.open(M.Id(),M.Jd)}catch(g){return c(g)}f.onupgradeneeded=function(){ea("creating db");f.result.createObjectStore(M.Kc)};f.onsuccess=function(){var g=f.result.transaction([M.Kc],"readwrite"),k=g.objectStore(M.Kc),m=0,q=0,p=a.length;a.forEach(function(r){r=k.put(M.rd(r).object.Ob,
r);r.onsuccess=function(){m++;m+q==p&&(0==q?b():c())};r.onerror=function(){q++;m+q==p&&(0==q?b():c())}});g.onerror=c};f.onerror=c},Pf:function(a,b,c){b=b||function(){};c=c||function(){};var d=M.indexedDB();try{var f=d.open(M.Id(),M.Jd)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=function(){var g=f.result;try{var k=g.transaction([M.Kc],"readonly")}catch(y){c(y);return}var m=k.objectStore(M.Kc),q=0,p=0,r=a.length;a.forEach(function(y){var F=m.get(y);F.onsuccess=function(){M.rd(y).exists&&M.unlink(y);
M.Od(Ob(y),Pb(y),F.result,!0,!0,!0);q++;q+p==r&&(0==p?b():c())};F.onerror=function(){p++;q+p==r&&(0==p?b():c())}});k.onerror=c};f.onerror=c}},ac={};
function bc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&Nb(b)!==Nb(M.oc(f.node)))return-54;throw f;}J[c>>2]=d.dev;J[c+4>>2]=0;J[c+8>>2]=d.ino;J[c+12>>2]=d.mode;J[c+16>>2]=d.nlink;J[c+20>>2]=d.uid;J[c+24>>2]=d.gid;J[c+28>>2]=d.rdev;J[c+32>>2]=0;T=[d.size>>>0,(S=d.size,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];J[c+40>>2]=T[0];J[c+44>>2]=T[1];J[c+48>>2]=4096;J[c+52>>2]=d.blocks;J[c+56>>2]=d.atime.getTime()/1E3|0;J[c+60>>
2]=0;J[c+64>>2]=d.mtime.getTime()/1E3|0;J[c+68>>2]=0;J[c+72>>2]=d.ctime.getTime()/1E3|0;J[c+76>>2]=0;T=[d.ino>>>0,(S=d.ino,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];J[c+80>>2]=T[0];J[c+84>>2]=T[1];return 0}var cc=void 0;function dc(){cc+=4;return J[cc-4>>2]}function ec(a){a=M.ec(a);if(!a)throw new M.Kb(8);return a}
function fc(a,b,c,d,f){if(u)return V(3,1,a,b,c,d,f);try{f=0;for(var g=b?J[b>>2]:0,k=b?J[b+4>>2]:0,m=c?J[c>>2]:0,q=c?J[c+4>>2]:0,p=d?J[d>>2]:0,r=d?J[d+4>>2]:0,y=0,F=0,n=0,v=0,w=0,N=0,Q=(b?J[b>>2]:0)|(c?J[c>>2]:0)|(d?J[d>>2]:0),ub=(b?J[b+4>>2]:0)|(c?J[c+4>>2]:0)|(d?J[d+4>>2]:0),G=0;G<a;G++){var R=1<<G%32;if(32>G?Q&R:ub&R){var Xa=M.ec(G);if(!Xa)throw new M.Kb(8);var Ya=5;Xa.Mb.Fc&&(Ya=Xa.Mb.Fc(Xa));Ya&1&&(32>G?g&R:k&R)&&(32>G?y|=R:F|=R,f++);Ya&4&&(32>G?m&R:q&R)&&(32>G?n|=R:v|=R,f++);Ya&2&&(32>G?p&R:
r&R)&&(32>G?w|=R:N|=R,f++)}}b&&(J[b>>2]=y,J[b+4>>2]=F);c&&(J[c>>2]=n,J[c+4>>2]=v);d&&(J[d>>2]=w,J[d+4>>2]=N);return f}catch(xb){return"undefined"!==typeof M&&xb instanceof M.Kb||z(xb),-xb.Nb}}
var O={Rb:function(){e.websocket=e.websocket&&"object"===typeof e.websocket?e.websocket:{};e.websocket.od={};e.websocket.on=function(a,b){"function"===typeof b&&(this.od[a]=b);return this};e.websocket.emit=function(a,b){"function"===typeof this.od[a]&&this.od[a].call(this,b)};return M.createNode(null,"/",16895,0)},createSocket:function(a,b,c){b&=-526337;c&&assert(1==b==(6==c));a={family:a,type:b,protocol:c,Ub:null,error:null,Rc:{},pending:[],Gc:[],ac:O.Xb};b=O.cd();c=M.createNode(O.root,b,49152,0);
c.Hc=a;b=M.Pd({path:b,node:c,flags:2,seekable:!1,Mb:O.Mb});a.stream=b;return a},Ne:function(a){return(a=M.ec(a))&&M.isSocket(a.node.mode)?a.node.Hc:null},Mb:{Fc:function(a){a=a.node.Hc;return a.ac.Fc(a)},Bc:function(a,b,c){a=a.node.Hc;return a.ac.Bc(a,b,c)},read:function(a,b,c,d){a=a.node.Hc;d=a.ac.ge(a,d);if(!d)return 0;b.set(d.buffer,c);return d.buffer.length},write:function(a,b,c,d){a=a.node.Hc;return a.ac.ke(a,b,c,d)},close:function(a){a=a.node.Hc;a.ac.close(a)}},cd:function(){O.cd.current||(O.cd.current=
0);return"socket["+O.cd.current++ +"]"},Xb:{Xc:function(a,b,c){if("object"===typeof b){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var f=e.websocket&&"object"===typeof e.websocket,g="ws:#".replace("#","//");f&&"string"===typeof e.websocket.url&&(g=e.websocket.url);if("ws://"===g||"wss://"===g){var k=
b.split("/");g=g+k[0]+":"+c+"/"+k.slice(1).join("/")}k="binary";f&&"string"===typeof e.websocket.subprotocol&&(k=e.websocket.subprotocol);var m=void 0;"null"!==k&&(k=k.replace(/^ +| +$/g,"").split(/ *, */),m=t?{protocol:k.toString()}:k);f&&null===e.websocket.subprotocol&&(m=void 0);d=new (t?require("ws"):WebSocket)(g,m);d.binaryType="arraybuffer"}catch(q){throw new M.Kb(23);}b={Sb:b,port:c,socket:d,Yc:[]};O.Xb.Ld(a,b);O.Xb.Oe(a,b);2===a.type&&"undefined"!==typeof a.xc&&b.Yc.push(new Uint8Array([255,
255,255,255,112,111,114,116,(a.xc&65280)>>8,a.xc&255]));return b},Zc:function(a,b,c){return a.Rc[b+":"+c]},Ld:function(a,b){a.Rc[b.Sb+":"+b.port]=b},he:function(a,b){delete a.Rc[b.Sb+":"+b.port]},Oe:function(a,b){function c(){e.websocket.emit("open",a.stream.fd);try{for(var g=b.Yc.shift();g;)b.socket.send(g),g=b.Yc.shift()}catch(k){b.socket.close()}}function d(g){if("string"===typeof g)g=(new TextEncoder).encode(g);else{assert(void 0!==g.byteLength);if(0==g.byteLength)return;g=new Uint8Array(g)}var k=
f;f=!1;k&&10===g.length&&255===g[0]&&255===g[1]&&255===g[2]&&255===g[3]&&112===g[4]&&111===g[5]&&114===g[6]&&116===g[7]?(g=g[8]<<8|g[9],O.Xb.he(a,b),b.port=g,O.Xb.Ld(a,b)):(a.Gc.push({Sb:b.Sb,port:b.port,data:g}),e.websocket.emit("message",a.stream.fd))}var f=!0;t?(b.socket.on("open",c),b.socket.on("message",function(g,k){k.Bf&&d((new Uint8Array(g)).buffer)}),b.socket.on("close",function(){e.websocket.emit("close",a.stream.fd)}),b.socket.on("error",function(){a.error=14;e.websocket.emit("error",[a.stream.fd,
a.error,"ECONNREFUSED: Connection refused"])})):(b.socket.onopen=c,b.socket.onclose=function(){e.websocket.emit("close",a.stream.fd)},b.socket.onmessage=function(g){d(g.data)},b.socket.onerror=function(){a.error=14;e.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})},Fc:function(a){if(1===a.type&&a.Ub)return a.pending.length?65:0;var b=0,c=1===a.type?O.Xb.Zc(a,a.Zb,a.bc):null;if(a.Gc.length||!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=
65;if(!c||c&&c.socket.readyState===c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=16;return b},Bc:function(a,b,c){switch(b){case 21531:return b=0,a.Gc.length&&(b=a.Gc[0].data.length),J[c>>2]=b,0;default:return 28}},close:function(a){if(a.Ub){try{a.Ub.close()}catch(f){}a.Ub=null}for(var b=Object.keys(a.Rc),c=0;c<b.length;c++){var d=a.Rc[b[c]];try{d.socket.close()}catch(f){}O.Xb.he(a,d)}return 0},bind:function(a,b,c){if("undefined"!==typeof a.gd||
"undefined"!==typeof a.xc)throw new M.Kb(28);a.gd=b;a.xc=c;if(2===a.type){a.Ub&&(a.Ub.close(),a.Ub=null);try{a.ac.listen(a,0)}catch(d){if(!(d instanceof M.Kb))throw d;if(138!==d.Nb)throw d;}}},connect:function(a,b,c){if(a.Ub)throw new M.Kb(138);if("undefined"!==typeof a.Zb&&"undefined"!==typeof a.bc){var d=O.Xb.Zc(a,a.Zb,a.bc);if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new M.Kb(7);throw new M.Kb(30);}}b=O.Xb.Xc(a,b,c);a.Zb=b.Sb;a.bc=b.port;throw new M.Kb(26);},listen:function(a){if(!t)throw new M.Kb(138);
if(a.Ub)throw new M.Kb(28);var b=require("ws").Server;a.Ub=new b({host:a.gd,port:a.xc});e.websocket.emit("listen",a.stream.fd);a.Ub.on("connection",function(c){if(1===a.type){var d=O.createSocket(a.family,a.type,a.protocol);c=O.Xb.Xc(d,c);d.Zb=c.Sb;d.bc=c.port;a.pending.push(d);e.websocket.emit("connection",d.stream.fd)}else O.Xb.Xc(a,c),e.websocket.emit("connection",a.stream.fd)});a.Ub.on("closed",function(){e.websocket.emit("close",a.stream.fd);a.Ub=null});a.Ub.on("error",function(){a.error=23;
e.websocket.emit("error",[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},accept:function(a){if(!a.Ub)throw new M.Kb(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Mf:function(a,b){if(b){if(void 0===a.Zb||void 0===a.bc)throw new M.Kb(53);b=a.Zb;a=a.bc}else b=a.gd||0,a=a.xc||0;return{Sb:b,port:a}},ke:function(a,b,c,d,f,g){if(2===a.type){if(void 0===f||void 0===g)f=a.Zb,g=a.bc;if(void 0===f||void 0===g)throw new M.Kb(17);}else f=a.Zb,g=a.bc;var k=O.Xb.Zc(a,f,g);if(1===
a.type){if(!k||k.socket.readyState===k.socket.CLOSING||k.socket.readyState===k.socket.CLOSED)throw new M.Kb(53);if(k.socket.readyState===k.socket.CONNECTING)throw new M.Kb(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);var m;b instanceof SharedArrayBuffer?m=(new Uint8Array(new Uint8Array(b.slice(c,c+d)))).buffer:m=b.slice(c,c+d);if(2===a.type&&(!k||k.socket.readyState!==k.socket.OPEN))return k&&k.socket.readyState!==k.socket.CLOSING&&k.socket.readyState!==k.socket.CLOSED||(k=O.Xb.Xc(a,f,
g)),k.Yc.push(m),d;try{return k.socket.send(m),d}catch(q){throw new M.Kb(28);}},ge:function(a,b){if(1===a.type&&a.Ub)throw new M.Kb(53);var c=a.Gc.shift();if(!c){if(1===a.type){if(a=O.Xb.Zc(a,a.Zb,a.bc)){if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null;throw new M.Kb(6);}throw new M.Kb(53);}throw new M.Kb(6);}var d=c.data.byteLength||c.data.length,f=c.data.byteOffset||0,g=c.data.buffer||c.data;b=Math.min(b,d);var k={buffer:new Uint8Array(g,f,b),Sb:c.Sb,
port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(g,f+b,d-b),a.Gc.unshift(c));return k}}};function X(a){a=O.Ne(a);if(!a)throw new M.Kb(8);return a}function hc(a){a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0}
function ic(a){var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(/[.]/g,":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-
1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"===typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=jc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]}
function kc(a,b,c,d,f){switch(b){case 2:c=hc(c);f&&(J[f>>2]=16);I[a>>1]=b;J[a+4>>2]=c;I[a+2>>1]=jc(d);T=[0,(S=0,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];J[a+8>>2]=T[0];J[a+12>>2]=T[1];break;case 10:c=ic(c);f&&(J[f>>2]=28);J[a>>2]=b;J[a+8>>2]=c[0];J[a+12>>2]=c[1];J[a+16>>2]=c[2];J[a+20>>2]=c[3];I[a+2>>1]=jc(d);J[a+4>>2]=0;J[a+24>>2]=0;break;default:return 5}return 0}var lc=1,mc={},nc={};
function oc(a){var b=hc(a);if(null!==b)return a;b=ic(a);if(null!==b)return a;mc[a]?b=mc[a]:(b=lc++,assert(65535>b,"exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),nc[b]=a,mc[a]=b);return b}function pc(a,b,c,d){if(u)return V(4,1,a,b,c,d);try{var f=X(a),g=f.ac.accept(f);b&&kc(b,g.family,oc(g.Zb),g.bc,c);return g.stream.fd}catch(k){return"undefined"!==typeof M&&k instanceof M.Kb||z(k),-k.Nb}}
function qc(a,b){if(u)return V(5,1,a,b);try{a=D(a);if(b&-8)var c=-28;else{var d;(d=M.Pb(a,{cc:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&M.pc(d,a)?-2:0):c=-44}return c}catch(f){return"undefined"!==typeof M&&f instanceof M.Kb||z(f),-f.Nb}}function rc(a){return(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255)}
function sc(a){var b="",c,d=0,f=0,g=0,k=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var m=!0;for(c=0;5>c;c++)if(0!==a[c]){m=!1;break}if(m){c=rc(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-f&&(k=0),f=c,k++),k>d&&(d=k,g=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=g&&c<g+d?c===g&&(b+=":",0===g&&(b+=":")):(b+=Number(tc(a[c]&65535)).toString(16),b+=7>c?":":"");return b}
function uc(a,b){var c=I[a>>1],d=tc(Ma[a+2>>1]);switch(c){case 2:if(16!==b)return{Nb:28};a=J[a+4>>2];a=rc(a);break;case 10:if(28!==b)return{Nb:28};a=[J[a+8>>2],J[a+12>>2],J[a+16>>2],J[a+20>>2]];a=sc(a);break;default:return{Nb:5}}return{family:c,Sb:a,port:d}}function vc(a,b,c){if(c&&0===a)return null;a=uc(a,b);if(a.Nb)throw new M.Kb(a.Nb);b=a.Sb;a.Sb=(nc[b]?nc[b]:null)||a.Sb;return a}
function wc(a,b,c){if(u)return V(6,1,a,b,c);try{var d=X(a),f=vc(b,c);d.ac.bind(d,f.Sb,f.port);return 0}catch(g){return"undefined"!==typeof M&&g instanceof M.Kb||z(g),-g.Nb}}function xc(a,b,c){if(u)return V(7,1,a,b,c);try{var d=X(a),f=vc(b,c);d.ac.connect(d,f.Sb,f.port);return 0}catch(g){return"undefined"!==typeof M&&g instanceof M.Kb||z(g),-g.Nb}}
function yc(a,b,c){if(u)return V(8,1,a,b,c);cc=c;try{var d=ec(a);switch(b){case 0:var f=dc();return 0>f?-28:M.open(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=dc(),d.flags|=f,0;case 12:return f=dc(),I[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return J[Db()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof M&&g instanceof M.Kb||z(g),-g.Nb}}
function zc(a,b){if(u)return V(9,1,a,b);try{var c=ec(a);return bc(M.stat,c.path,b)}catch(d){return"undefined"!==typeof M&&d instanceof M.Kb||z(d),-d.Nb}}
function Ac(a,b,c){if(u)return V(10,1,a,b,c);try{var d=ec(a);d.sc||(d.sc=M.readdir(d.path));a=0;for(var f=M.$b(d,0,1),g=Math.floor(f/280);g<d.sc.length&&a+280<=c;){var k=d.sc[g];if("."===k[0]){var m=1;var q=4}else{var p=M.hc(d.node,k);m=p.id;q=M.Nc(p.mode)?2:M.Tb(p.mode)?4:M.tc(p.mode)?10:8}T=[m>>>0,(S=m,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];J[b+a>>2]=T[0];J[b+a+4>>2]=T[1];T=[280*(g+1)>>>0,(S=280*(g+1),1<=+Math.abs(S)?
0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];J[b+a+8>>2]=T[0];J[b+a+12>>2]=T[1];I[b+a+16>>1]=280;B[b+a+18>>0]=q;Da(k,A,b+a+19,256);a+=280;g+=1}M.$b(d,280*g,0);return a}catch(r){return"undefined"!==typeof M&&r instanceof M.Kb||z(r),-r.Nb}}function Bc(a,b,c){if(u)return V(11,1,a,b,c);try{var d=X(a);if(!d.Zb)return-53;kc(b,d.family,oc(d.Zb),d.bc,c);return 0}catch(f){return"undefined"!==typeof M&&f instanceof M.Kb||z(f),-f.Nb}}
function Cc(a,b){if(u)return V(12,1,a,b);try{return Dc(b,0,136),J[b>>2]=1,J[b+4>>2]=2,J[b+8>>2]=3,J[b+12>>2]=4,0}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Nb}}function Ec(a,b,c){if(u)return V(13,1,a,b,c);try{h("__sys_getsockname "+a);var d=X(a);kc(b,d.family,oc(d.gd||"0.0.0.0"),d.xc,c);return 0}catch(f){return"undefined"!==typeof M&&f instanceof M.Kb||z(f),-f.Nb}}
function Fc(a,b,c,d,f){if(u)return V(14,1,a,b,c,d,f);try{var g=X(a);return 1===b&&4===c?(J[d>>2]=g.error,J[f>>2]=4,g.error=null,0):-50}catch(k){return"undefined"!==typeof M&&k instanceof M.Kb||z(k),-k.Nb}}
function Gc(a,b,c){if(u)return V(15,1,a,b,c);cc=c;try{var d=ec(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=dc();return J[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=dc(),M.Bc(d,b,f);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:z("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof M&&g instanceof M.Kb||z(g),-g.Nb}}
function Hc(a,b){if(u)return V(16,1,a,b);try{var c=X(a);c.ac.listen(c,b);return 0}catch(d){return"undefined"!==typeof M&&d instanceof M.Kb||z(d),-d.Nb}}function Ic(a,b){if(u)return V(17,1,a,b);try{return a=D(a),bc(M.lstat,a,b)}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Nb}}function Jc(a,b){if(u)return V(18,1,a,b);try{return a=D(a),a=Nb(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),M.mkdir(a,b,0),0}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Nb}}
function Kc(a,b,c,d,f,g){if(u)return V(19,1,a,b,c,d,f,g);try{a:{g<<=12;var k=!1;if(0!==(d&16)&&0!==a%65536)var m=-28;else{if(0!==(d&32)){var q=Lc(65536,b);if(!q){m=-48;break a}Dc(q,0,b);k=!0}else{var p=M.ec(f);if(!p){m=-8;break a}var r=M.Cc(p,a,b,g,c,d);q=r.gf;k=r.pd}ac[q]={Xe:q,Ue:b,pd:k,fd:f,ff:c,flags:d,offset:g};m=q}}return m}catch(y){return"undefined"!==typeof M&&y instanceof M.Kb||z(y),-y.Nb}}
function Mc(a,b){if(u)return V(20,1,a,b);try{if(-1===(a|0)||0===b)var c=-28;else{var d=ac[a];if(d&&b===d.Ue){var f=M.ec(d.fd);if(f&&d.ff&2){var g=d.flags,k=d.offset,m=A.slice(a,a+b);M.Dc(f,m,k,b,g)}ac[a]=null;d.pd&&sb(d.Xe)}c=0}return c}catch(q){return"undefined"!==typeof M&&q instanceof M.Kb||z(q),-q.Nb}}function Nc(a,b,c){if(u)return V(21,1,a,b,c);cc=c;try{var d=D(a),f=c?dc():0;return M.open(d,b,f).fd}catch(g){return"undefined"!==typeof M&&g instanceof M.Kb||z(g),-g.Nb}}
function Oc(a,b,c){if(u)return V(22,1,a,b,c);try{for(var d=c=0;d<b;d++){var f=a+8*d,g=I[f+4>>1],k=32,m=M.ec(J[f>>2]);m&&(k=5,m.Mb.Fc&&(k=m.Mb.Fc(m)));(k&=g|24)&&c++;I[f+6>>1]=k}return c}catch(q){return"undefined"!==typeof M&&q instanceof M.Kb||z(q),-q.Nb}}function Pc(a,b,c,d){if(u)return V(23,1,a,b,c,d);try{return d&&(J[d>>2]=-1,J[d+4>>2]=-1,J[d+8>>2]=-1,J[d+12>>2]=-1),0}catch(f){return"undefined"!==typeof M&&f instanceof M.Kb||z(f),-f.Nb}}
function Qc(a,b,c,d,f,g){if(u)return V(24,1,a,b,c,d,f,g);try{var k=X(a),m=k.ac.ge(k,c);if(!m)return 0;f&&kc(f,k.family,oc(m.Sb),m.port,g);A.set(m.buffer,b);return m.buffer.byteLength}catch(q){return"undefined"!==typeof M&&q instanceof M.Kb||z(q),-q.Nb}}function Rc(a,b){if(u)return V(25,1,a,b);try{return a=D(a),b=D(b),M.rename(a,b),0}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Nb}}
function Sc(a){if(u)return V(26,1,a);try{return a=D(a),M.rmdir(a),0}catch(b){return"undefined"!==typeof M&&b instanceof M.Kb||z(b),-b.Nb}}function Tc(a,b,c,d,f,g){if(u)return V(27,1,a,b,c,d,f,g);try{var k=X(a),m=vc(f,g,!0);return m?k.ac.ke(k,B,b,c,m.Sb,m.port):M.write(k.stream,B,b,c)}catch(q){return"undefined"!==typeof M&&q instanceof M.Kb||z(q),-q.Nb}}function Uc(a){return u?V(28,1,a):-50}
function Vc(a,b){if(u)return V(29,1,a,b);try{return X(a),-52}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Nb}}function Wc(a,b,c){if(u)return V(30,1,a,b,c);try{return O.createSocket(a,b,c).stream.fd}catch(d){return"undefined"!==typeof M&&d instanceof M.Kb||z(d),-d.Nb}}function Xc(a,b){if(u)return V(31,1,a,b);try{return a=D(a),bc(M.stat,a,b)}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Nb}}
function Yc(a){if(u)return V(32,1,a);try{return a=D(a),M.unlink(a),0}catch(b){return"undefined"!==typeof M&&b instanceof M.Kb||z(b),-b.Nb}}function Zc(){void 0===Zc.start&&(Zc.start=Date.now());return 1E3*(Date.now()-Zc.start)|0}var $c=[];
function ad(){t||l||(ua||(ua={}),ua["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(ua["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,h("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function bd(a,b,c){if(0>=a||a>B.length||a&1)return-28;if(la){if(Atomics.load(J,a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(J,lb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(J,lb>>2,0),-73;d=Atomics.exchange(J,lb>>2,0);if(0==d)break;vb();if(Atomics.load(J,a>>2)!=b)return-6;Atomics.exchange(J,lb>>2,a)}return 0}a=Atomics.wait(J,a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function V(a,b){for(var c=arguments.length-2,d=C(),f=Ca(8*c),g=f>>3,k=0;k<c;k++)Oa[g+k]=arguments[2+k];c=cd(a,c,f,b);E(d);return c}var dd=[],ed=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function fd(a){a=2<a?D(a):a;return ed[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function gd(a,b,c){var d=fd(a);if(!d)return-4;d.Wc&&(J[d.Wc>>2]=b,J[d.Wc+4>>2]=c);if(d.ee||!d.Ef)d.ee&&(d=d.ee),a=!1,d.Vc&&d.Vc.Uc&&(a=d.Vc.Uc.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Vc.Uc.viewport(0,0,b,c);else{if(d.Wc){d=J[d.Wc+8>>2];a=a?D(a):"";var f=C(),g=Ca(12),k=0;if(a){k=Ha(a)+1;var m=H(k);Da(a,A,m,k);k=m}J[g>>2]=k;J[g+4>>2]=b;J[g+8>>2]=c;hd(0,d,657457152,0,k,g);E(f);return 1}return-4}return 0}
function jd(a,b,c){return u?V(33,1,a,b,c):gd(a,b,c)}function kd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,k){b.drawElementsInstancedANGLE(c,d,f,g,k)})}
function ld(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function md(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function nd(a,b){a.Xd||(a.Xd=a.getContext,a.getContext=function(d,f){f=a.Xd(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?od(c,b):0}function od(a,b){var c=H(8);J[c+4>>2]=qb();var d={Nf:c,attributes:b,version:b.We,Uc:a};a.canvas&&(a.canvas.Vc=d);("undefined"===typeof b.Sd||b.Sd)&&pd(d);return c}
function pd(a){a||(a=qd);if(!a.Pe){a.Pe=!0;var b=a.Uc;kd(b);ld(b);md(b);b.If=b.getExtension("EXT_disjoint_timer_query");b.Tf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var qd,rd=["default","low-power","high-performance"],sd={};
function td(){if(!ud){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ja||"./this.program"},b;for(b in sd)void 0===sd[b]?delete a[b]:a[b]=sd[b];var c=[];for(b in a)c.push(b+"="+a[b]);ud=c}return ud}var ud;
function vd(a,b){if(u)return V(34,1,a,b);try{var c=0;td().forEach(function(d,f){var g=b+c;J[a+4*f>>2]=g;Ka(d,g);c+=d.length+1});return 0}catch(d){return"undefined"!==typeof M&&d instanceof M.Kb||z(d),d.Nb}}function wd(a,b){if(u)return V(35,1,a,b);try{var c=td();J[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});J[b>>2]=d;return 0}catch(f){return"undefined"!==typeof M&&f instanceof M.Kb||z(f),f.Nb}}
function xd(a){if(u)return V(36,1,a);try{var b=ec(a);M.close(b);return 0}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),c.Nb}}function yd(a,b){if(u)return V(37,1,a,b);try{var c=ec(a);B[b>>0]=c.tty?2:M.Tb(c.mode)?3:M.tc(c.mode)?7:4;return 0}catch(d){return"undefined"!==typeof M&&d instanceof M.Kb||z(d),d.Nb}}
function zd(a,b,c,d){if(u)return V(38,1,a,b,c,d);try{a:{for(var f=ec(a),g=a=0;g<c;g++){var k=J[b+(8*g+4)>>2],m=M.read(f,B,J[b+8*g>>2],k,void 0);if(0>m){var q=-1;break a}a+=m;if(m<k)break}q=a}J[d>>2]=q;return 0}catch(p){return"undefined"!==typeof M&&p instanceof M.Kb||z(p),p.Nb}}
function Ad(a,b,c,d,f){if(u)return V(39,1,a,b,c,d,f);try{var g=ec(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;M.$b(g,a,d);T=[g.position>>>0,(S=g.position,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];J[f>>2]=T[0];J[f+4>>2]=T[1];g.sc&&0===a&&0===d&&(g.sc=null);return 0}catch(k){return"undefined"!==typeof M&&k instanceof M.Kb||z(k),k.Nb}}
function Bd(a,b,c,d){if(u)return V(40,1,a,b,c,d);try{a:{for(var f=ec(a),g=a=0;g<c;g++){var k=M.write(f,B,J[b+8*g>>2],J[b+(8*g+4)>>2],void 0);if(0>k){var m=-1;break a}a+=k}m=a}J[d>>2]=m;return 0}catch(q){return"undefined"!==typeof M&&q instanceof M.Kb||z(q),q.Nb}}var Y={};
function Cd(a){Cd.buffer||(Cd.buffer=H(256),Y["0"]="Success",Y["-1"]="Invalid value for 'ai_flags' field",Y["-2"]="NAME or SERVICE is unknown",Y["-3"]="Temporary failure in name resolution",Y["-4"]="Non-recoverable failure in name res",Y["-6"]="'ai_family' not supported",Y["-7"]="'ai_socktype' not supported",Y["-8"]="SERVICE not supported for 'ai_socktype'",Y["-10"]="Memory allocation failure",Y["-11"]="System error returned in 'errno'",Y["-12"]="Argument buffer overflow");var b="Unknown error";a in
Y&&(255<Y[a].length?b="Message too long":b=Y[a]);Ka(b,Cd.buffer);return Cd.buffer}
function Dd(a,b,c,d){function f(y,F,n,v,w,N){var Q=10===y?28:16;w=10===y?sc(w):rc(w);Q=H(Q);w=kc(Q,y,w,N);assert(!w);w=H(32);J[w+4>>2]=y;J[w+8>>2]=F;J[w+12>>2]=n;J[w+24>>2]=v;J[w+20>>2]=Q;J[w+16>>2]=10===y?28:16;J[w+28>>2]=0;return w}if(u)return V(41,1,a,b,c,d);var g=0,k=0,m=0,q=0,p=0,r=0;c&&(m=J[c>>2],q=J[c+4>>2],p=J[c+8>>2],r=J[c+12>>2]);p&&!r&&(r=2===p?17:6);!p&&r&&(p=17===r?2:1);0===r&&(r=6);0===p&&(p=1);if(!a&&!b)return-2;if(m&-1088||0!==c&&J[c>>2]&2&&!a)return-1;if(m&32)return-2;if(0!==p&&1!==
p&&2!==p)return-7;if(0!==q&&2!==q&&10!==q)return-6;if(b&&(b=D(b),k=parseInt(b,10),isNaN(k)))return m&1024?-2:-8;if(!a)return 0===q&&(q=2),0===(m&1)&&(2===q?g=Ed(2130706433):g=[0,0,0,1]),a=f(q,p,r,null,g,k),J[d>>2]=a,0;a=D(a);g=hc(a);if(null!==g)if(0===q||2===q)q=2;else if(10===q&&m&8)g=[0,0,Ed(65535),g],q=10;else return-2;else if(g=ic(a),null!==g)if(0===q||10===q)q=10;else return-2;if(null!=g)return a=f(q,p,r,a,g,k),J[d>>2]=a,0;if(m&4)return-2;a=oc(a);g=hc(a);0===q?q=2:10===q&&(g=[0,0,Ed(65535),g]);
a=f(q,p,r,null,g,k);J[d>>2]=a;return 0}
function wb(a){if(u)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=U.Me();if(!b)return 6;if(void 0!==b.dc)throw"Internal error!";if(!a.dd)throw"Internal error, no pthread ptr!";U.qc.push(b);for(var c=H(512),d=0;128>d;++d)J[c+4*d>>2]=0;var f=a.yc+a.Ic;d=U.kc[a.dd]={worker:b,yc:a.yc,Ic:a.Ic,qd:a.qd,lc:a.dd};var g=d.lc>>2;Atomics.store(K,g+16,a.detached);Atomics.store(K,g+25,c);Atomics.store(K,g+10,d.lc);Atomics.store(K,g+20,a.Ic);Atomics.store(K,g+19,
f);Atomics.store(K,g+26,a.Ic);Atomics.store(K,g+28,f);Atomics.store(K,g+29,a.detached);c=Fd()+40;Atomics.store(K,g+43,c);b.dc=d;var k={cmd:"run",start_routine:a.nf,arg:a.Ac,threadInfoStruct:a.dd,stackBase:a.yc,stackSize:a.Ic};b.Sc=function(){k.time=performance.now();b.postMessage(k,a.yf)};b.loaded&&(b.Sc(),delete b.Sc);return 0}
function Gd(a,b){if(!a)return h("pthread_join attempted on a null thread pointer!"),71;if(u&&qb()==a)return h("PThread "+a+" is attempting to join to itself!"),16;if(!u&&Hd()==a)return h("Main thread "+a+" is attempting to join to itself!"),16;if(J[a+12>>2]!==a)return h("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(K,a+64>>2))return h("Attempted to join thread "+a+", which was already detached!"),28;for(ad();;){var c=
Atomics.load(K,a>>2);if(1==c)return c=Atomics.load(K,a+4>>2),b&&(J[b>>2]=c),Atomics.store(K,a+64>>2,1),u?postMessage({cmd:"cleanupThread",thread:a}):nb(a),0;if(u){var d=qb();if(d&&!Atomics.load(K,d+56>>2)&&2==Atomics.load(K,d+0>>2))throw"Canceled!";}u||vb();bd(a,c,u?100:1)}}function Id(a){return 0===a%4&&(0!==a%100||0===a%400)}function Jd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Kd=[31,29,31,30,31,30,31,31,30,31,30,31],Ld=[31,28,31,30,31,30,31,31,30,31,30,31];
function Md(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Id(a.getFullYear())?Kd:Ld)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}function Nd(a,b,c,d){a||(a=this);this.parent=a;this.Rb=a.Rb;this.Pc=null;this.id=M.af++;this.name=b;this.mode=c;this.Lb={};this.Mb={};this.rdev=d}
Object.defineProperties(Nd.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Te:{get:function(){return M.Tb(this.mode)}},zd:{get:function(){return M.Nc(this.mode)}}});M.ne=Nd;M.pf();var $b,Od=[null,Eb,Hb,fc,pc,qc,wc,xc,yc,zc,Ac,Bc,Cc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,jd,vd,wd,xd,yd,zd,Ad,Bd,Dd];
function Xb(a,b){var c=Array(Ha(a)+1);a=Da(a,c,0,c.length);b&&(c.length=a);return c}
var he={c:function(a,b,c,d){z("Assertion failed: "+D(a)+", at: "+[b?D(b):"unknown filename",c,d?D(d):"unknown function"])},Ja:function(a,b){a=Pd(a,b);if(!Ab())return postMessage({cmd:"exitProcess",returnCode:a}),a},K:function(a,b){return Cb(a,b)},F:function(a,b){return Eb(a,b)},Qa:function(a,b){return Fb(a,b)},na:function(a,b){return Gb(a,b)},ma:function(a,b){return Lb(a,b)},ya:fc,ca:pc,Ba:qc,fa:wc,ea:xc,q:yc,Ga:zc,ra:Ac,aa:Bc,ua:Cc,ba:Ec,Z:Fc,P:Gc,da:Hc,Ha:Ic,Ia:Jc,pa:Kc,qa:function(){return 0},
oa:Mc,Ea:function(){return-63},R:Nc,xa:Oc,ta:Pc,_:Qc,Fa:Rc,Ca:Sc,$:Tc,sa:function(){return 0},_a:Uc,ga:Vc,J:Wc,S:Xc,va:function(a){try{if(!a)return-21;var b={__size__:390,domainname:325,machine:260,nodename:65,release:130,sysname:0,version:195};Ka("Emscripten",a+b.sysname);Ka("emscripten",a+b.nodename);Ka("1.0",a+b.release);Ka("#1",a+b.version);Ka("wasm32",a+b.machine);return 0}catch(c){return"undefined"!==typeof M&&c instanceof M.Kb||z(c),-c.Nb}},Da:Yc,Oa:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});
else if(u)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=U.kc[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},ja:function(){throw"longjmp";},b:function(){z()},Pa:Zc,Ta:Cb,X:function(){z("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Ua:function(){z("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},
U:function(a,b,c){$c.length=0;var d;for(c>>=2;d=A[b++];)(d=105>d)&&c&1&&c++,$c.push(d?Oa[c++>>1]:J[c]),++c;return jb[a].apply(null,$c)},wa:ad,C:function(){},w:bd,v:kb,za:function(){return A.length},u:Bb,ha:function(a,b,c){A.copyWithin(a,b,b+c)},Aa:function(){return t?require("os").cpus().length:navigator.hardwareConcurrency},La:function(a,b,c){dd.length=b;c>>=3;for(var d=0;d<b;d++)dd[d]=Oa[c+d];return(0>a?jb[-a-1]:Od[a]).apply(null,dd)},ia:function(){z("OOM")},Ma:function(a,b,c){return fd(a)?gd(a,
b,c):jd(a,b,c)},T:function(){},Ka:function(){},Na:function(a,b){b>>=2;b={alpha:!!J[b],depth:!!J[b+1],stencil:!!J[b+2],antialias:!!J[b+3],premultipliedAlpha:!!J[b+4],preserveDrawingBuffer:!!J[b+5],powerPreference:rd[J[b+6]],failIfMajorPerformanceCaveat:!!J[b+7],We:J[b+8],Rf:J[b+9],Sd:J[b+10],He:J[b+11],Wf:J[b+12],Xf:J[b+13]};a=fd(a);return!a||b.He?0:nd(a,b)},ka:vd,la:wd,B:function(a){da(a)},A:xd,O:yd,Q:zd,Va:Ad,E:Bd,x:Cd,d:function(){return va},t:Dd,r:function(a,b,c,d,f,g,k){b=uc(a,b);if(b.Nb)return-6;
a=b.port;var m=b.Sb;b=!1;if(c&&d){var q;if(k&1||!(q=nc[m]?nc[m]:null)){if(k&8)return-2}else m=q;c=Da(m,A,c,d);c+1>=d&&(b=!0)}f&&g&&(c=Da(""+a,A,f,g),c+1>=g&&(b=!0));return b?-12:0},i:function(a){var b=Date.now();J[a>>2]=b/1E3|0;J[a+4>>2]=b%1E3*1E3|0;return 0},o:Gb,Za:function(){U.Qe()},Y:Qd,h:Rd,g:Sd,y:Td,I:Ud,W:Vd,H:Wd,Xa:Xd,Wa:Yd,j:Zd,s:$d,D:ae,f:be,G:ce,Sa:de,V:ee,Ya:fe,n:Lb,a:xa||e.wasmMemory,N:function(a){Hb();var b=new Date(J[a+20>>2]+1900,J[a+16>>2],J[a+12>>2],J[a+8>>2],J[a+4>>2],J[a>>2],0),
c=J[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),k=f.getTimezoneOffset(),m=Math.min(k,g);0>c?J[a+32>>2]=Number(g!=k&&m==d):0<c!=(m==d)&&(g=Math.max(k,g),b.setTime(b.getTime()+6E4*((0<c?m:g)-d)));J[a+24>>2]=b.getDay();J[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;J[a>>2]=b.getSeconds();J[a+4>>2]=b.getMinutes();J[a+8>>2]=b.getHours();J[a+12>>2]=b.getDate();J[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},Ra:function(a){if(a===
Hd())return h("Main thread (id="+a+") cannot be canceled!"),71;if(!a)return h("pthread_cancel attempted on a null thread pointer!"),71;if(J[a+12>>2]!==a)return h("pthread_cancel attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;Atomics.compareExchange(K,a>>2,0,2);u?postMessage({cmd:"cancelThread",thread:a}):mb(a);return 0},L:function(a){var b=U.jd.pop();a&&b()},M:Fb,l:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return h("Current environment does not support SharedArrayBuffer, pthreads are not available!"),
6;if(!a)return h("pthread_create called with a null thread pointer!"),28;var f=[];if(u&&0===f.length)return ge(687865856,a,b,c,d);var g=0,k=0;if(b&&-1!=b){var m=J[b>>2];m+=81920;g=J[b+8>>2];k=0!==J[b+12>>2]}else m=2097152;(b=0==g)?g=Lc(16,m):(g-=m,assert(0<g));for(var q=H(228),p=0;57>p;++p)K[(q>>2)+p]=0;J[a>>2]=q;J[q+12>>2]=q;a=q+152;J[a>>2]=a;c={yc:g,Ic:m,qd:b,detached:k,nf:c,dd:q,Ac:d,yf:f};return u?(c.Df="spawnThread",postMessage(c,f),0):wb(c)},m:function(a,b){return Gd(a,b)},e:function(a){va=
a},z:function(){return 0},k:function(a,b,c,d){function f(n,v,w){for(n="number"===typeof n?n.toString():n||"";n.length<v;)n=w[0]+n;return n}function g(n,v){return f(n,v,"0")}function k(n,v){function w(Q){return 0>Q?-1:0<Q?1:0}var N;0===(N=w(n.getFullYear()-v.getFullYear()))&&0===(N=w(n.getMonth()-v.getMonth()))&&(N=w(n.getDate()-v.getDate()));return N}function m(n){switch(n.getDay()){case 0:return new Date(n.getFullYear()-1,11,29);case 1:return n;case 2:return new Date(n.getFullYear(),0,3);case 3:return new Date(n.getFullYear(),
0,2);case 4:return new Date(n.getFullYear(),0,1);case 5:return new Date(n.getFullYear()-1,11,31);case 6:return new Date(n.getFullYear()-1,11,30)}}function q(n){n=Md(new Date(n.Yb+1900,0,1),n.md);var v=new Date(n.getFullYear()+1,0,4),w=m(new Date(n.getFullYear(),0,4));v=m(v);return 0>=k(w,n)?0>=k(v,n)?n.getFullYear()+1:n.getFullYear():n.getFullYear()-1}var p=J[d+40>>2];d={wf:J[d>>2],vf:J[d+4>>2],kd:J[d+8>>2],Tc:J[d+12>>2],Jc:J[d+16>>2],Yb:J[d+20>>2],ld:J[d+24>>2],md:J[d+28>>2],$f:J[d+32>>2],uf:J[d+
36>>2],xf:p?D(p):""};c=D(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in p)c=c.replace(new RegExp(r,"g"),p[r]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
F="January February March April May June July August September October November December".split(" ");p={"%a":function(n){return y[n.ld].substring(0,3)},"%A":function(n){return y[n.ld]},"%b":function(n){return F[n.Jc].substring(0,3)},"%B":function(n){return F[n.Jc]},"%C":function(n){return g((n.Yb+1900)/100|0,2)},"%d":function(n){return g(n.Tc,2)},"%e":function(n){return f(n.Tc,2," ")},"%g":function(n){return q(n).toString().substring(2)},"%G":function(n){return q(n)},"%H":function(n){return g(n.kd,
2)},"%I":function(n){n=n.kd;0==n?n=12:12<n&&(n-=12);return g(n,2)},"%j":function(n){return g(n.Tc+Jd(Id(n.Yb+1900)?Kd:Ld,n.Jc-1),3)},"%m":function(n){return g(n.Jc+1,2)},"%M":function(n){return g(n.vf,2)},"%n":function(){return"\n"},"%p":function(n){return 0<=n.kd&&12>n.kd?"AM":"PM"},"%S":function(n){return g(n.wf,2)},"%t":function(){return"\t"},"%u":function(n){return n.ld||7},"%U":function(n){var v=new Date(n.Yb+1900,0,1),w=0===v.getDay()?v:Md(v,7-v.getDay());n=new Date(n.Yb+1900,n.Jc,n.Tc);return 0>
k(w,n)?g(Math.ceil((31-w.getDate()+(Jd(Id(n.getFullYear())?Kd:Ld,n.getMonth()-1)-31)+n.getDate())/7),2):0===k(w,v)?"01":"00"},"%V":function(n){var v=new Date(n.Yb+1901,0,4),w=m(new Date(n.Yb+1900,0,4));v=m(v);var N=Md(new Date(n.Yb+1900,0,1),n.md);return 0>k(N,w)?"53":0>=k(v,N)?"01":g(Math.ceil((w.getFullYear()<n.Yb+1900?n.md+32-w.getDate():n.md+1-w.getDate())/7),2)},"%w":function(n){return n.ld},"%W":function(n){var v=new Date(n.Yb,0,1),w=1===v.getDay()?v:Md(v,0===v.getDay()?1:7-v.getDay()+1);n=
new Date(n.Yb+1900,n.Jc,n.Tc);return 0>k(w,n)?g(Math.ceil((31-w.getDate()+(Jd(Id(n.getFullYear())?Kd:Ld,n.getMonth()-1)-31)+n.getDate())/7),2):0===k(w,v)?"01":"00"},"%y":function(n){return(n.Yb+1900).toString().substring(2)},"%Y":function(n){return n.Yb+1900},"%z":function(n){n=n.uf;var v=0<=n;n=Math.abs(n)/60;return(v?"+":"-")+String("0000"+(n/60*100+n%60)).slice(-4)},"%Z":function(n){return n.xf},"%%":function(){return"%"}};for(r in p)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),p[r](d)));r=Xb(c,
!1);if(r.length>b)return 0;B.set(r,a);return r.length-1},p:function(a){var b=Date.now()/1E3|0;a&&(J[a>>2]=b);return b}};
(function(){function a(f,g){e.asm=f.exports;L=e.asm.cb;Sa.unshift(e.asm.$a);U.Hd.push(e.asm.jb);ya=g;u||eb()}function b(f){a(f.instance,f.module)}function c(f){return hb().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){h("failed to asynchronously prepare wasm: "+g);z(g)})}var d={a:he};u||db();if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return h("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return wa||"function"!==typeof WebAssembly.instantiateStreaming||
fb()||P.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(P,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){h("wasm streaming compile failed: "+g);h("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.$a).apply(null,arguments)};
var sb=e._free=function(){return(sb=e._free=e.asm.ab).apply(null,arguments)},H=e._malloc=function(){return(H=e._malloc=e.asm.bb).apply(null,arguments)},Db=e.___errno_location=function(){return(Db=e.___errno_location=e.asm.db).apply(null,arguments)};e._fflush=function(){return(e._fflush=e.asm.eb).apply(null,arguments)};
var Lc=e._memalign=function(){return(Lc=e._memalign=e.asm.fb).apply(null,arguments)},tc=e._ntohs=function(){return(tc=e._ntohs=e.asm.gb).apply(null,arguments)},jc=e._htons=function(){return(jc=e._htons=e.asm.hb).apply(null,arguments)},Pd=e._main=function(){return(Pd=e._main=e.asm.ib).apply(null,arguments)};e._emscripten_tls_init=function(){return(e._emscripten_tls_init=e.asm.jb).apply(null,arguments)};var qb=e._pthread_self=function(){return(qb=e._pthread_self=e.asm.kb).apply(null,arguments)};
e._emscripten_current_thread_process_queued_calls=function(){return(e._emscripten_current_thread_process_queued_calls=e.asm.lb).apply(null,arguments)};
var pb=e._emscripten_register_main_browser_thread_id=function(){return(pb=e._emscripten_register_main_browser_thread_id=e.asm.mb).apply(null,arguments)},Hd=e._emscripten_main_browser_thread_id=function(){return(Hd=e._emscripten_main_browser_thread_id=e.asm.nb).apply(null,arguments)},ib=e.__emscripten_do_dispatch_to_thread=function(){return(ib=e.__emscripten_do_dispatch_to_thread=e.asm.ob).apply(null,arguments)},ge=e._emscripten_sync_run_in_main_thread_4=function(){return(ge=e._emscripten_sync_run_in_main_thread_4=
e.asm.pb).apply(null,arguments)},vb=e._emscripten_main_thread_process_queued_calls=function(){return(vb=e._emscripten_main_thread_process_queued_calls=e.asm.qb).apply(null,arguments)},cd=e._emscripten_run_in_main_runtime_thread_js=function(){return(cd=e._emscripten_run_in_main_runtime_thread_js=e.asm.rb).apply(null,arguments)},hd=e.__emscripten_call_on_thread=function(){return(hd=e.__emscripten_call_on_thread=e.asm.sb).apply(null,arguments)};
e._emscripten_proxy_main=function(){return(e._emscripten_proxy_main=e.asm.tb).apply(null,arguments)};
var ob=e.__emscripten_thread_init=function(){return(ob=e.__emscripten_thread_init=e.asm.ub).apply(null,arguments)},Dc=e._memset=function(){return(Dc=e._memset=e.asm.vb).apply(null,arguments)},rb=e.___pthread_tsd_run_dtors=function(){return(rb=e.___pthread_tsd_run_dtors=e.asm.wb).apply(null,arguments)},Fd=e._emscripten_get_global_libc=function(){return(Fd=e._emscripten_get_global_libc=e.asm.xb).apply(null,arguments)},Ed=e._htonl=function(){return(Ed=e._htonl=e.asm.yb).apply(null,arguments)},Kb=e.__get_tzname=
function(){return(Kb=e.__get_tzname=e.asm.zb).apply(null,arguments)},Jb=e.__get_daylight=function(){return(Jb=e.__get_daylight=e.asm.Ab).apply(null,arguments)},Ib=e.__get_timezone=function(){return(Ib=e.__get_timezone=e.asm.Bb).apply(null,arguments)},C=e.stackSave=function(){return(C=e.stackSave=e.asm.Cb).apply(null,arguments)},E=e.stackRestore=function(){return(E=e.stackRestore=e.asm.Db).apply(null,arguments)},Ca=e.stackAlloc=function(){return(Ca=e.stackAlloc=e.asm.Eb).apply(null,arguments)},yb=
e._emscripten_stack_set_limits=function(){return(yb=e._emscripten_stack_set_limits=e.asm.Fb).apply(null,arguments)},Z=e._setThrew=function(){return(Z=e._setThrew=e.asm.Gb).apply(null,arguments)},ie=e.dynCall_vijjjid=function(){return(ie=e.dynCall_vijjjid=e.asm.Hb).apply(null,arguments)},je=e.dynCall_iiiijj=function(){return(je=e.dynCall_iiiijj=e.asm.Ib).apply(null,arguments)},ke=e.dynCall_iij=function(){return(ke=e.dynCall_iij=e.asm.Jb).apply(null,arguments)};e._ff_h264_cabac_tables=2558924;
var tb=e.__emscripten_allow_main_runtime_queued_calls=5410016,lb=e.__emscripten_main_thread_futex=16979940;function Sd(a,b,c){var d=C();try{return L.get(a)(b,c)}catch(f){E(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Zd(a,b){var c=C();try{L.get(a)(b)}catch(d){E(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function be(a,b,c,d,f){var g=C();try{L.get(a)(b,c,d,f)}catch(k){E(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}
function $d(a,b,c){var d=C();try{L.get(a)(b,c)}catch(f){E(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Rd(a,b){var c=C();try{return L.get(a)(b)}catch(d){E(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function Ud(a,b,c,d,f){var g=C();try{return L.get(a)(b,c,d,f)}catch(k){E(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function Wd(a,b,c,d,f,g,k,m,q){var p=C();try{return L.get(a)(b,c,d,f,g,k,m,q)}catch(r){E(p);if(r!==r+0&&"longjmp"!==r)throw r;Z(1,0)}}
function ae(a,b,c,d){var f=C();try{L.get(a)(b,c,d)}catch(g){E(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function Qd(a){var b=C();try{return L.get(a)()}catch(c){E(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}function ce(a,b,c,d,f,g){var k=C();try{L.get(a)(b,c,d,f,g)}catch(m){E(k);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}}function Td(a,b,c,d){var f=C();try{return L.get(a)(b,c,d)}catch(g){E(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}
function Vd(a,b,c,d,f,g){var k=C();try{return L.get(a)(b,c,d,f,g)}catch(m){E(k);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}}function ee(a,b,c,d,f,g,k,m,q){var p=C();try{L.get(a)(b,c,d,f,g,k,m,q)}catch(r){E(p);if(r!==r+0&&"longjmp"!==r)throw r;Z(1,0)}}function de(a,b,c,d,f,g,k){var m=C();try{L.get(a)(b,c,d,f,g,k)}catch(q){E(m);if(q!==q+0&&"longjmp"!==q)throw q;Z(1,0)}}function fe(a,b,c,d,f,g,k,m,q,p){var r=C();try{ie(a,b,c,d,f,g,k,m,q,p)}catch(y){E(r);if(y!==y+0&&"longjmp"!==y)throw y;Z(1,0)}}
function Xd(a,b,c,d,f,g,k,m){var q=C();try{return je(a,b,c,d,f,g,k,m)}catch(p){E(q);if(p!==p+0&&"longjmp"!==p)throw p;Z(1,0)}}function Yd(a,b,c,d){var f=C();try{return ke(a,b,c,d)}catch(g){E(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}e.ccall=Ba;e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(g){return"number"===g});return"string"!==b&&f&&!d?Aa(a):function(){return Ba(a,b,c,arguments,d)}};
e.setValue=function(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":B[a>>0]=b;break;case "i8":B[a>>0]=b;break;case "i16":I[a>>1]=b;break;case "i32":J[a>>2]=b;break;case "i64":T=[b>>>0,(S=b,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];J[a>>2]=T[0];J[a+4>>2]=T[1];break;case "float":Na[a>>2]=b;break;case "double":Oa[a>>3]=b;break;default:z("invalid type for setValue: "+c)}};e.writeAsciiToMemory=Ka;
e.FS=M;e.PThread=U;e.PThread=U;e.wasmMemory=xa;e.ExitStatus=ca;var le;function ca(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}cb=function me(){le||ne();le||(cb=me)};
function ne(a){function b(){if(!le&&(le=!0,e.calledRun=!0,!za)){Wa();u||Za(Ta);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(oe){var c=a,d=e._emscripten_proxy_main;c=c||[];var f=c.length+1,g=Ca(4*(f+1));J[g>>2]=Ja(ja);for(var k=1;k<f;k++)J[(g>>2)+k]=Ja(c[k-1]);J[(g>>2)+f]=0;d(f,g)}if(!u){if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),Va.unshift(c);Za(Va)}}}a=a||ia;if(!(0<ab))if(u)aa(e),Wa(),postMessage({cmd:"loaded"});else{if(!u){if(e.preRun)for("function"==
typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)$a();Za(Ra)}0<ab||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=ne;function da(a,b){if(!b||!Ab()||0!==a){if(!b&&u)throw postMessage({cmd:"exitProcess",returnCode:a}),new ca(a);if(!Ab()){U.qf();u||(Za(Ua),M.quit(),U.ie());if(e.onExit)e.onExit(a);za=!0}ka(a,new ca(a))}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();
var oe=!1;e.noInitialRun&&(oe=!1);u&&(noExitRuntime=!1,U.Re());ne();


  return createFFmpegCore.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createFFmpegCore;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createFFmpegCore; });
else if (typeof exports === 'object')
  exports["createFFmpegCore"] = createFFmpegCore;
